# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jelovnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=80)),
                ('jela', models.ManyToManyField(blank=True, null=True, to='jela.Jelo')),
            ],
        ),
    ]
