# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelovnik',
            name='jela',
            field=models.ManyToManyField(blank=True, to='jela.Jelo'),
        ),
    ]
