# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restorani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menadzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=120)),
                ('prezime', models.CharField(max_length=120)),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restoran')),
            ],
        ),
    ]
