# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pice',
            name='restoran',
        ),
        migrations.AlterField(
            model_name='pice',
            name='image',
            field=models.ImageField(upload_to='pica/images/'),
        ),
    ]
