# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restorani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=80)),
                ('opis', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=100)),
                ('restoran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restoran')),
            ],
        ),
    ]
