# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jela', '0002_auto_20160411_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelo',
            name='image',
            field=models.ImageField(upload_to='jela/images/'),
        ),
        migrations.AlterField(
            model_name='jelo',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restoran'),
        ),
    ]
