# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jela', '0003_auto_20160417_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jelo',
            name='restoran',
        ),
    ]
