# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jela', '0006_auto_20160419_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
