# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kartaPica', '0001_initial'),
        ('pica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartapica',
            name='pica',
            field=models.ManyToManyField(blank=True, to='pica.Pice'),
        ),
    ]
